import Head from 'next/head'
import ArticleList from '../components/ArticleList'

export default function Home({articles}) {
 console.log(articles)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ArticleList  articles={articles} />
        
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch(`https://jsonplaceholder.typicode.com/posts?_limit=12`)
  const articles = await res.json()
  return {
    props: {
      articles
    }
  }
}
